version: '3'

volumes:
  unity-accelerator.v2-volume:
    driver: 'local'

services:
  unity-accelerator.v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: unity-accelerator.v2:v1.0.54
    volumes:
      - unity-accelerator.v2-volume:/root/.config/unity-accelerator
    ports:
      - "10080:10080"
